# Generated by Django 5.2.6 on 2025-09-30 12:39

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('one_room', 'One Room'), ('self_contained', 'Self Contained'), ('one_bedroom', 'One Bedroom'), ('two_bedrooms', 'Two Bedrooms'), ('three_bedrooms', 'Three Bedrooms')], default=None, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(editable=False, max_length=255, null=True)),
                ('normalized_capital_name', models.CharField(editable=False, max_length=255, null=True)),
                ('capital_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TextNormalizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(default=None, editable=False, max_length=255, null=True)),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='listings.state')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TextNormalizationMixin, models.Model),
        ),
    ]
