# Generated by Django 5.0.3 on 2025-09-30 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentForRent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('initial_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments_for_rent', to='listings.apartmenttype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments_for_rent', to='listings.region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments_for_rent', to='listings.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApartmentForSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('square_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments_for_sale', to='listings.region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments_for_sale', to='listings.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plot_size', models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=10)),
                ('titled', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lands', to='listings.region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lands', to='listings.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
