# Generated by Django 5.0.3 on 2025-09-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_apartmentforrent_apartmentforsale_land'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentforsale',
            name='square_feet',
        ),
        migrations.AddField(
            model_name='apartmentforsale',
            name='apartment_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartments_for_sale', to='listings.apartmenttype'),
        ),
    ]
