# Generated by Django 5.0.3 on 2025-09-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_apartmentforsale_square_feet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentforsale',
            name='apartment_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='apartments_for_sale', to='listings.apartmenttype'),
        ),
    ]
