# Generated by Django 5.0.3 on 2025-09-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_apartmentforsale_apartment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentforsale',
            name='apartment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments_for_sale', to='listings.apartmenttype'),
        ),
    ]
