# Generated by Django 5.0.3 on 2025-09-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_apartmentforsale_apartment_type'),
        ('users', '0004_agent_client_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentforrent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments_for_rent_by_agent', to='users.agent'),
        ),
        migrations.AddField(
            model_name='apartmentforrent',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments_for_rent_by_landlord', to='users.landlord'),
        ),
        migrations.AddField(
            model_name='apartmentforsale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments_for_sale_by_agent', to='users.agent'),
        ),
        migrations.AddField(
            model_name='apartmentforsale',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments_for_sale_by_landlord', to='users.landlord'),
        ),
        migrations.AddField(
            model_name='land',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands_for_sale_by_agent', to='users.agent'),
        ),
        migrations.AddField(
            model_name='land',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands_for_sale_by_landlord', to='users.landlord'),
        ),
    ]
