# Generated by Django 5.0.3 on 2025-10-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_apartmentforrent_agent_apartmentforrent_landlord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
