# Generated by Django 5.0.3 on 2025-10-01 04:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentForRentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='apartments_for_rent/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('apartment_for_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.apartmentforrent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApartmentForSaleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='apartments_for_sale/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('apartment_for_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.apartmentforsale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='lands/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.land')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
