# Generated by Django 5.0.3 on 2025-10-01 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_apartmentforrentimage_apartmentforsaleimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentforrentimage',
            name='image',
            field=models.FileField(upload_to='apartments_for_rent/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'tif', 'webp', 'svg', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='apartmentforsaleimage',
            name='image',
            field=models.FileField(upload_to='apartments_for_sale/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'tif', 'webp', 'svg', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='landimage',
            name='image',
            field=models.FileField(upload_to='lands/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'tif', 'webp', 'svg', 'heic', 'heif'])]),
        ),
    ]
