# Generated by Django 5.0.3 on 2025-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('AGENT', 'Agent'), ('CLIENT', 'Client'), ('LANDLORD', 'Landlord')], default='GUEST', max_length=50),
        ),
    ]
