# Generated by Django 5.0.3 on 2025-09-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='authentication_means',
            field=models.CharField(choices=[('email', 'Email'), ('facebook', 'Facebook'), ('google', 'Google')], default='email', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('agent', 'Agent'), ('client', 'Client'), ('landlord', 'Landlord')], default='guest', max_length=50),
        ),
    ]
